AuthServer/Controllers/OIDC/AuthorizationController.cs
using System.Security.Claims;
using AuthServer.Attributes;
using AuthServer.Extensions;
using AuthServer.Infrastructure.Context;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Primitives;
using OpenIddict.Abstractions;
using OpenIddict.Server.AspNetCore;
using SharedLibrary.Infrastructure.DataTransferObjects;
using static OpenIddict.Abstractions.OpenIddictConstants;

namespace AuthServer.Controllers.OIDC;

public class AuthorizationController : Controller
{
    private readonly IOpenIddictApplicationManager _applicationManager;
    private readonly IOpenIddictAuthorizationManager _authorizationManager;
    private readonly AuthContext _context;
    private readonly IOpenIddictScopeManager _scopeManager;

    public AuthorizationController(
        AuthContext context,
        IOpenIddictApplicationManager applicationManager,
        IOpenIddictAuthorizationManager authorizationManager,
        IOpenIddictScopeManager scopeManager
    )
    {
        _context = context;
        _applicationManager = applicationManager;
        _authorizationManager = authorizationManager;
        _scopeManager = scopeManager;
    }

    [HttpPost("~/connect/token")]
    [Produces("application/json")]
    public async Task<IActionResult> Exchange()
    {
        var request = HttpContext.GetOpenIddictServerRequest()
                      ?? throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");

        if (request.IsAuthorizationCodeGrantType() || request.IsRefreshTokenGrantType())
            return await HandleExchangeCodeGrantType();

        if (request.IsClientCredentialsGrantType())
            // The client credentials are automatically validated by OpenIddict,
            // if client_id or client_secret are invalid, this action won't be invoked.
            return await HandleExchangeClientCredentialsGrantType(request);

        throw new InvalidOperationException("The specific grant type is not supported");
    }

    [HttpGet("~/connect/authorize")]
    [HttpPost("~/connect/authorize")]
    [IgnoreAntiforgeryToken]
    public async Task<IActionResult> Authorize()
    {
        var request = HttpContext.GetOpenIddictServerRequest()
                      ?? throw new InvalidOperationException("The OpenID Connect request cannot be retrieved");

        // If prompt=login was specified by the client application,
        // immediately return the user agent to the login page.
        if (request.HasPrompt(Prompts.Login))
        {
            var prompt = string.Join(" ", request.GetPrompts().Remove(Prompts.Login));
            var parameters = Request.HasFormContentType
                ? Request.Form.Where(parameter => parameter.Key != Parameters.Prompt).ToList()
                : Request.Query.Where(parameter => parameter.Key != Parameters.Prompt).ToList();

            parameters.Add(KeyValuePair.Create(Parameters.Prompt, new StringValues(prompt)));

            return Challenge(
                authenticationSchemes: CookieAuthenticationDefaults.AuthenticationScheme,
                properties: new AuthenticationProperties
                {
                    RedirectUri = Request.PathBase + Request.Path + QueryString.Create(
                        Request.HasFormContentType ? Request.Form.ToList() : Request.Query.ToList())
                });
        }

        // Retrieve the user principal store in the authentication cookie.
        // If a max_age parameter was provided, ensure that the cookie is not too old.
        // If the user principal can't be extracted or the cookie is too old,
        // redirect the user agent to the login page.
        var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (result == null ||
            !result.Succeeded ||
            (request.MaxAge != null &&
             result.Properties?.IssuedUtc != null &&
             DateTimeOffset.UtcNow - result.Properties.IssuedUtc > TimeSpan.FromSeconds(request.MaxAge.Value)))
        {
            if (request.HasPrompt(Prompts.None))
                return Forbid(
                    authenticationSchemes: OpenIddictServerAspNetCoreDefaults.AuthenticationScheme,
                    properties: new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.LoginRequired,
                        [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] = "The user is not logged in."
                    }));

            return Challenge(
                authenticationSchemes: CookieAuthenticationDefaults.AuthenticationScheme,
                properties: new AuthenticationProperties
                {
                    RedirectUri = Request.PathBase + Request.Path + QueryString.Create(
                        Request.HasFormContentType ? Request.Form.ToList() : Request.Query.ToList())
                });
        }

        if (!int.TryParse(result.Principal.GetClaim(ClaimTypes.NameIdentifier), out var userId))
            throw new InvalidOperationException("UserId is invalid");

        var user = await _context.Users.FirstOrDefaultAsync(m => m.Id == userId);
        if (user == null) throw new InvalidOperationException("User is invalid");

        var application = await _applicationManager.FindByClientIdAsync(request.ClientId
                                                                        ?? throw new InvalidOperationException(
                                                                            "Detials concerning the calling client application cannot be found"));

        var authorizations = await _authorizationManager.FindAsync(
            userId.ToString(),
            await _applicationManager.GetIdAsync(application),
            Statuses.Valid,
            AuthorizationTypes.Permanent,
            request.GetScopes()).ToListAsync();

        switch (await _applicationManager.GetConsentTypeAsync(application))
        {
            // If the consent is external (e.g. when authorizations are granted by a sysadmin),
            // immediately return an error if no authorizations can be found in the database.
            case ConsentTypes.External when !authorizations.Any():
                return Forbid(
                    authenticationSchemes: OpenIddictServerAspNetCoreDefaults.AuthenticationScheme,
                    properties: new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.ConsentRequired,
                        [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] =
                            "The logged in user is not allowed to access this client application."
                    }));

            // If the consent is implicit or if an authorizations was found,
            // return an authorizations response without displaying the consent form.
            case ConsentTypes.Implicit:
            case ConsentTypes.External when authorizations.Any():
            case ConsentTypes.Explicit when authorizations.Any() && !request.HasPrompt(Prompts.Consent):
                // Convert to an OpenIddict Claim
                var claims = new List<Claim>
                {
                    new(Claims.Subject, userId.ToString())
                };

                var claimsIdentity =
                    new ClaimsIdentity(claims, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
                claimsIdentity.SetDestinations(GetDestinations);

                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                claimsPrincipal.SetScopes(request.GetScopes());
                claimsPrincipal.SetResources(await _scopeManager.ListResourcesAsync(claimsPrincipal.GetScopes())
                    .ToListAsync());

                var authorization = authorizations.LastOrDefault();
                authorization ??= await _authorizationManager.CreateAsync(
                    claimsPrincipal,
                    userId.ToString(),
                    await _applicationManager.GetIdAsync(application),
                    AuthorizationTypes.Permanent,
                    claimsPrincipal.GetScopes());

                claimsPrincipal.SetAuthorizationId(await _authorizationManager.GetIdAsync(authorization));

                return SignIn(claimsPrincipal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);

            // At this point, no authorization was found in the database and an error must be returned
            // if the client application specified prompt=none in the authorization request.
            case ConsentTypes.Explicit when request.HasPrompt(Prompts.None):
            case ConsentTypes.Systematic when request.HasPrompt(Prompts.None):
                return Forbid(
                    authenticationSchemes: OpenIddictServerAspNetCoreDefaults.AuthenticationScheme,
                    properties: new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.ConsentRequired,
                        [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] =
                            "Interactive user consent is required."
                    }));

            // In every other case, render the consent form.
            default:
                return View(new ConsentFormDto
                {
                    ApplicationName = await _applicationManager.GetDisplayNameAsync(application),
                    Scope = request.Scope
                });
        }
    }

    [Authorize]

AuthServer/Views/Authorization/Authorize.cshtml
@using Microsoft.Extensions.Primitives
@model ConsentFormDto

<div class="flex flex-row justify-center mt-52">
    <div class="flex flex-col w-[350px]">
        <h1 class="text-4xl font-bold">Authorization</h1>

        <hr class="my-4"/>

        <form asp-action="Authorize" asp-controller="Authorization" method="post" class="flex flex-col gap-4">
            <div>
                Do you want to grant <strong>@Model.ApplicationName</strong>
                access to your data? (scopes requested: @Model.Scope)
            </div>

            @* Flow the request parameters so they can be received by the Accpet/Reject actions *@
            @foreach (var parameter in Context.Request.HasFormContentType ?
                (IEnumerable<KeyValuePair<string, StringValues>>)Context.Request.Form : Context.Request.Query)
            {
                <input type="hidden" name="@parameter.Key" value="@parameter.Value"/>
            }

            <div class="flex justify-between">
                <span></span>
                <div>
                    <input type="submit" name="submit.Accept" value="No" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2"/>
                    <input type="submit" name="submit.Accept" value="Yes" class="flex justify-between text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center"/>
                </div>
            </div>
        </form>
    </div>
</div>

AuthServer/Views/Authorization/Logout.cshtml
@using Microsoft.Extensions.Primitives
@{
    ViewData["Title"] = "Logout";
}

<div class="flex flex-row justify-center mt-52">
    <div class="flex flex-col w-[350px]">
        <h1 class="text-4xl font-bold">Logout</h1>

        <hr class="my-4"/>

        <form asp-action="Logout" asp-controller="Authorization" method="post" class="flex flex-col gap-4">
            <div>
                Are you sure you want to sign out?
            </div>

            @* Flow the request parameters so they can be received by the LogoutPost action: *@
            @foreach (var parameter in Context.Request.HasFormContentType ?
                (IEnumerable<KeyValuePair<string, StringValues>>)Context.Request.Form : Context.Request.Query)
            {
                <input type="hidden" name="@parameter.Key" value="@parameter.Value"/>
            }

            <div class="flex justify-between">
                <span></span>
                <div>
                    <input type="submit" value="Yes" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2"/>
                </div>
            </div>
        </form>
    </div>
</div>